import { MessOverallSummary, MemberCalculationSummary } from './calculations';
import { formatBdt } from './bengali-utils';

export function generateWhatsAppMessReport(
  monthYear: string,
  summary: MessOverallSummary
): string {
  const [year, month] = monthYear.split('-');
  const monthName = new Date(Number(year), Number(month) - 1, 1).toLocaleString('default', {
    month: 'long',
    year: 'numeric',
  });

  const lines: string[] = [];

  lines.push(`🍽️ *MESS MEAL & EXPENSE STATEMENT* 🍽️`);
  lines.push(`📅 *Month:* ${monthName}`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`📊 *OVERALL OVERVIEW:*`);
  lines.push(`• Total Meals: *${summary.grandTotalMeals}*`);
  lines.push(`• Total Bazar: *${formatBdt(summary.totalBazarExpense)}*`);
  lines.push(`• Meal Rate: *${formatBdt(summary.mealRate)} / meal*`);
  lines.push(`• Shared Utilities (Wifi, Gas, Current): *${formatBdt(summary.totalUtilitiesExpense)}*`);
  lines.push(`• Total Deposits Collected: *${formatBdt(summary.totalDeposits)}*`);
  lines.push(`• Mess Fund Cash in Hand: *${formatBdt(summary.fundCashInHand)}*`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`👤 *MEMBER BREAKDOWN & SETTLEMENT:*`);

  summary.memberSummaries.forEach((m: MemberCalculationSummary, index: number) => {
    const displayName = m.member.bnName ? `${m.member.name} (${m.member.bnName})` : m.member.name;
    const balanceAmount = Math.abs(m.balance);
    let balanceText = '';

    if (m.status === 'refund') {
      balanceText = `🟢 *মেস থেকে পাবে (Refund): ${formatBdt(balanceAmount)}*`;
    } else if (m.status === 'due') {
      balanceText = `🔴 *মেসে দিতে হবে (Due): ${formatBdt(balanceAmount)}*`;
    } else {
      balanceText = `⚪ *হিসাব সম্পন্ন (Settled)*`;
    }

    lines.push(`\n${index + 1}. *${displayName}*`);
    lines.push(`   - Meals: ${m.totalMeals} (${formatBdt(m.mealCost)})`);
    lines.push(`   - Utility Share: ${formatBdt(m.utilityShare)}`);
    lines.push(`   - Total Cost: ${formatBdt(m.totalCost)}`);
    lines.push(`   - Paid/Deposit: ${formatBdt(m.totalPaid)}`);
    lines.push(`   👉 ${balanceText}`);
  });

  lines.push(`\n━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`Generated by *MessMeal* App`);

  return lines.join('\n');
}
