import { MessOverallSummary, MemberCalculationSummary } from './calculations';
import { formatBdt } from './bengali-utils';

export function generateWhatsAppMessReport(
  monthYear: string,
  summary: MessOverallSummary,
  style: 'bangla' | 'english' | 'compact' = 'bangla'
): string {
  const [year, month] = monthYear.split('-');
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  const monthName = `${monthNames[Number(month) - 1]} ${year}`;

  const lines: string[] = [];

  if (style === 'compact') {
    lines.push(`📋 *মেস হিসাব - ${monthName}*`);
    lines.push(`মিল রেট: *${formatBdt(summary.mealRate)}* | মোট মিল: *${summary.grandTotalMeals}* | বাজার: *${formatBdt(summary.totalBazarExpense)}*`);
    lines.push(`────────────────────`);
    summary.memberSummaries.forEach((m) => {
      const name = m.member.bnName || m.member.name;
      const bal = Math.abs(m.balance);
      const sign = m.status === 'refund' ? '🟢 পাবে' : m.status === 'due' ? '🔴 দিবে' : '⚪ সমান';
      lines.push(`${name}: মিল ${m.totalMeals} (${formatBdt(m.mealCost)}) | ${sign} ${formatBdt(bal)}`);
    });
    lines.push(`────────────────────`);
    lines.push(`হাতে ক্যাশ: *${formatBdt(summary.fundCashInHand)}*`);
    return lines.join('\n');
  }

  lines.push(`🍽️ *MESS MEAL & EXPENSE STATEMENT* 🍽️`);
  lines.push(`📅 *Month:* ${monthName}`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`📊 *সারসংক্ষেপ (OVERVIEW):*`);
  lines.push(`• মোট মিল (Total Meals): *${summary.grandTotalMeals}*`);
  lines.push(`• মোট বাজার খরচ (Total Bazar): *${formatBdt(summary.totalBazarExpense)}*`);
  lines.push(`• মিল রেট (Meal Rate): *${formatBdt(summary.mealRate)} / meal*`);
  lines.push(`• শেয়ার্ড ইউটিলিটি (Wifi, Gas, Current): *${formatBdt(summary.totalUtilitiesExpense)}*`);
  lines.push(`• মোট জমা সংগ্রহ (Deposits): *${formatBdt(summary.totalDeposits)}*`);
  lines.push(`• মেস ফান্ডে অবশিষ্ট ক্যাশ (Cash in Hand): *${formatBdt(summary.fundCashInHand)}*`);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`👤 *সদস্যদের হিসাব ও নিষ্পত্তি (FINAL SETTLEMENT):*`);

  summary.memberSummaries.forEach((m: MemberCalculationSummary, index: number) => {
    const displayName = m.member.bnName ? `${m.member.name} (${m.member.bnName})` : m.member.name;
    const balanceAmount = Math.abs(m.balance);
    let balanceText = '';

    if (m.status === 'refund') {
      balanceText = `🟢 *মেস থেকে ফেরত পাবে: ${formatBdt(balanceAmount)}*`;
    } else if (m.status === 'due') {
      balanceText = `🔴 *মেসে জমা দিতে হবে (বকেয়া): ${formatBdt(balanceAmount)}*`;
    } else {
      balanceText = `⚪ *হিসাব সম্পন্ন (Settled)*`;
    }

    lines.push(`\n${index + 1}. *${displayName}*`);
    lines.push(`   - মিল: ${m.totalMeals} টি = ${formatBdt(m.mealCost)}`);
    lines.push(`   - শেয়ার্ড বিল (ইউটিলিটি): ${formatBdt(m.utilityShare)}`);
    lines.push(`   - মোট খরচ: ${formatBdt(m.totalCost)}`);
    lines.push(`   - জমা/পরিশোধ: ${formatBdt(m.totalPaid)}`);
    lines.push(`   👉 ${balanceText}`);
  });

  lines.push(`\n━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`Generated by *MessMeal* App`);

  return lines.join('\n');
}

/**
 * Generates CSV content and triggers client-side download
 */
export function exportMessToCsv(monthYear: string, summary: MessOverallSummary) {
  const headers = [
    'Member Name',
    'Bangla Name',
    'Total Meals',
    'Meal Rate (BDT)',
    'Meal Cost (BDT)',
    'Utility Share (BDT)',
    'Total Cost (BDT)',
    'Total Paid/Deposited (BDT)',
    'Final Balance (BDT)',
    'Settlement Status',
  ];

  const rows = summary.memberSummaries.map((m) => [
    `"${m.member.name}"`,
    `"${m.member.bnName || ''}"`,
    m.totalMeals,
    summary.mealRate.toFixed(2),
    m.mealCost.toFixed(2),
    m.utilityShare.toFixed(2),
    m.totalCost.toFixed(2),
    m.totalPaid.toFixed(2),
    m.balance.toFixed(2),
    m.status === 'refund' ? 'Refund (Pabe)' : m.status === 'due' ? 'Due (Dibe)' : 'Settled',
  ]);

  const summaryRows = [
    [],
    ['--- MONTH SUMMARY ---'],
    ['Month', monthYear],
    ['Grand Total Meals', summary.grandTotalMeals],
    ['Total Bazar Expense (BDT)', summary.totalBazarExpense.toFixed(2)],
    ['Meal Rate (BDT)', summary.mealRate.toFixed(2)],
    ['Total Utilities (BDT)', summary.totalUtilitiesExpense.toFixed(2)],
    ['Total Deposits (BDT)', summary.totalDeposits.toFixed(2)],
    ['Fund Cash In Hand (BDT)', summary.fundCashInHand.toFixed(2)],
  ];

  const csvContent = [
    headers.join(','),
    ...rows.map((r) => r.join(',')),
    ...summaryRows.map((r) => r.join(',')),
  ].join('\n');

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `mess-statement-${monthYear}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
